title: Ayan Niftaliyeva | Portfolio
theme: jekyll-theme-minimal
description: Information Systems Student at ADA University
logo: /assets/images/profile-photo.jpeg

# Mandatory Profile Links for Footer Icons
github_username: ayanniftaliyeva
codecademy_username: ayashka25918
linkedin_username: ayan-niftaliyeva-5955a039a

# Custom Variables for our chic design
email: aniftaliyeva25918@ada.edu.az
repo_url: https://github.com/ayanniftaliyeva/site1101-portfolio